### ISSUE TITLE
Better readability and style of menus

### ISSUE THREAD

**Issue by stefa168** [tsi-unito/menu_bot#10]
Would it be possible to have the menus displayed in a less cluttered way, like with lists and separators?

**Comment by lory9894** [comment]
Noted, I'll try it

**Comment by lory9894** [comment]
ok, i'll leave here some resources for future me or enyone else willing to contribute (I should really be studying instead of doing telegram bots).
https://stackoverflow.com/questions/51125356/proper-way-to-build-menus-with-python-telegram-bot
https://github.com/mevellea/telegram_menu

**Comment by lory9894** [comment]
@lorenzodipi Questo si può fare praticamente facendo copia-incolla dal tuo bot

**Comment by lory9894** [comment]
#30 fornisce uno stile migliore dei menù.
