### ISSUE TITLE
File Admin

### ISSUE THREAD

**Issue by lorenzodipi** [tsi-unito/menu_bot#27]
Aggiungere un file admin in cui scrivere tutti gli id di coloro che possono usare i comandi "riservati".
Quando si richiama un metodo riservato il programma controlla se l'id esiste in quel file, così da poter avere più facilità nell'aggiungere o togliere Admin

**Comment by stefa168** [comment]
Ho notato che GH non chiude gli issue se non mettiamo "solves, closes, ecc." direttamente nel messaggio di commit, chiudo manualmente 🤓
